repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
  - repo: https://github.com/HunterMcGushion/docstr_coverage
    rev: v2.2.0
    hooks:
      - id: docstr-coverage
        args: ["--verbose", "2", "--accept-empty"]
  - repo: local
    hooks:
      - id: wily
        name: wily
        entry: wily diff
        verbose: true
        language: python
        additional_dependencies: [wily]
  - repo: https://github.com/asottile/dead
    rev: v1.5.0
    hooks:
      - id: dead
  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.1
    hooks:
      - id: pydocstyle
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5' # Update me!
    hooks:
    - id: bandit
